/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BookAMeetingRouteImport } from './routes/book-a-meeting'
import { Route as IndexRouteImport } from './routes/index'

const BookAMeetingRoute = BookAMeetingRouteImport.update({
  id: '/book-a-meeting',
  path: '/book-a-meeting',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/book-a-meeting': typeof BookAMeetingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/book-a-meeting': typeof BookAMeetingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/book-a-meeting': typeof BookAMeetingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/book-a-meeting'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/book-a-meeting'
  id: '__root__' | '/' | '/book-a-meeting'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookAMeetingRoute: typeof BookAMeetingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/book-a-meeting': {
      id: '/book-a-meeting'
      path: '/book-a-meeting'
      fullPath: '/book-a-meeting'
      preLoaderRoute: typeof BookAMeetingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookAMeetingRoute: BookAMeetingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
